apiVersion: v1
kind: Namespace
metadata:
    name: 11-ns
    labels:
       enviroment: test
       team: backend
    annotations:
       created: "Santosh-Mohanty"
       purpose: "Revesion_Test"
spec: 
  finalizers:
    - kubernetes