apiVersion: v1
kind: Service
metadata:
    name: 11-service
    namespace: 11-ns
    labels:
    app: webapp
    tier: frontend
    annotations:
      description: "Service exposing webapp Deployment internally"
spec:
  selector:
      app: 11-nginx
  type : ClusterIP
  ports:
    name: app2           # optional but recommended
    port: 80             # Service port (client-facing)
    targetPort: app2     # 👈 must match Deployment port name
    protocol: TCP

  #### Both are Valid

  ports: 
    port:80
    targetPort: 8080
    
