apiVersion: v1
kind: Service
metadata:
    name: 11-service
    namespace: 11-ns
    labels:
    app: webapp
    tier: frontend
    annotations:
      description: "Service exposing webapp Deployment internally"
spec:
  selector:
      app: 11-nginx
  type : ClusterIP
  ports:
    name: pod-service-port
    protocol: TCP
    port: 80
    targetPort: 80 #### here you can use the pod-port label
    
    
